
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.27428.2037
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "makefile", "makefile\makefile.csproj", "{4AF033E7-6519-4FBC-9516-9DABA40D3DF0}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{4AF033E7-6519-4FBC-9516-9DABA40D3DF0}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{4AF033E7-6519-4FBC-9516-9DABA40D3DF0}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{4AF033E7-6519-4FBC-9516-9DABA40D3DF0}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{4AF033E7-6519-4FBC-9516-9DABA40D3DF0}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {43EC9041-F7CC-4319-9FDA-F85E46B0F3D7}
	EndGlobalSection
EndGlobal
